### PR TITLE
Initial Python3 support

### PR DESCRIPTION
**Pull request by bmoscon**
Resolves all the errors that prevent tests from _running_ in python3. Still contains test _failures_ in python3 (73 fail, 97 pass). Obviously not great, but at least clears out the noise so that specific failures can be addressed. From the few hours I spent on this today, about 90% of the remaining issues are bytes vs strings differences between Python2 and Python3. When we converted Arctic to support Python3 these issues resulted in a lot of changes so I will probably need/want to get some input from the creators before making more changes.

### CODE REVIEW

**Comment by bmoscon** [comment]
Also, isnt there a way to get circle to run on all PRs? Was hoping it would run so I could double check I didn't break anything in Python2.7

**Comment by DominikMChrist** [comment]
I have enabled building of forks in CircleCI. Hope it works now.

**Comment by bmoscon** [comment]
thanks. I pushed a minor change to .gitignore to give it a whirl

**Comment by DominikMChrist** [comment]
Would it make sense to add tox for testing various python versions in a unified manner?

**Comment by bmoscon** [comment]
@DominikMChrist definitely would make sense to use tox. I have more experience with travis, but I'm sure I can get tox working. The 3.x env tests will currently fail, but at least with it up and running it will make it easier to have a go-to place to ID the current state of Python3 support. Will work on setting this up.

**Pull request merged**
