### PR TITLE
Use Tox for multi-env support 

### PR DESCRIPTION
**Pull request by bmoscon**
Use tox to support multiple versions of python

### CODE REVIEW

**Comment by bmoscon** [comment]
don't merge this in yet. I can't get it to run in circle unless I actually open a PR. Once it seems to be working I'll let you know

**Comment by bmoscon** [comment]
Ok. Tox is working now. Py3 has the failures you'd expect. 2.7 has a failure that appears in the tox virtualenv, but not in the circle container (unclear why).:

```
=================================== FAILURES ===================================
_______________________ test_PlotBase_write_dict_simple ________________________

plot = <pybloqs.plot.core.Plot object at 0x7fbe86b76ed0>

    def test_PlotBase_write_dict_simple(plot):
        chart_buf = StringIO()
        plot._write_dict(chart_buf, {"moof": 5, "poof": {"glop": 42}})
>       assert chart_buf.getvalue() == "{poof:{glop:42},moof:5}"
E       AssertionError: assert '{moof:5,poof:{glop:42}}' == '{poof:{glop:42},moof:5}'
E         - {moof:5,poof:{glop:42}}
E         + {poof:{glop:42},moof:5}

tests/unit/test_plot_unit.py:16: AssertionError
=============== 1 failed, 169 passed, 3 xfailed in 8.05 seconds ================
```

Looks it expects the dict ordering to always be the same?

**Comment by DominikMChrist** [comment]
This test is for a function that converts a dict to a string, therefore test is against a string and this fixes the order. When I run a loop on a dict in a python shell, I always get alphabetical order. But the following might make sure it's ordered (see line 481, core.py): 
```for i, item in enumerate(sorted(iteritems(d)):```
because when I do:
```for i, item in enumerate(sorted(iteritems(d),reverse=True)): ```
I get the items in reverse alphabetical order.

**Comment by bmoscon** [comment]
@DominikMChrist suddenly the dict test passes now . . . (i love non determinism). Anyways, assuming for a moment that we're ignoring that, surely you wouldnt want this merged in until Python3 support was finished? Should I just close this PR to remove some noise? Should I leave Tox in, but remove the Py3 env? Let me know your thoughts/plans

**Comment by DominikMChrist** [comment]
Tox support is great for future testing!

With 
python setup.py develop 
and
python setup.py load_highcharts 
you can run the tests locally, so I think there won't be too much noise anyway,

Totally fine to keep the PR open for now,

**Pull request closed without merging**
